config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'sessions#new'
  	
  # sign up page with form:
  get 'users/new' => 'users#new', as: :new_user

  # create (post) action for when sign up form is submitted:

  # resources :posts do
  #   collection do
  #     get :confirm_create, to: "posts#new"
  #     post :confirm_create
  #   end
  #   member do
  #     get :confirm_update, to: "posts#confirm_update"
  #     post :confirm_update
  #     post :update_post
  #   end
  # end


  # , only: [:index, :create, :update, :edit, :destroy]
  # get '/users' => 'users#index'
  #  get '/users/:id', to: 'users#profile'
  # log in page with form:
  get '/login'     => 'sessions#new'
  get '/register'     => 'users#register'
  post '/posts/import' => 'posts#import'

  post '/posts/confirm' => 'posts#confirm'
  
  post '/users/confirm' => 'users#confirm'
  post '/posts/confirm_update' => 'posts#confirm_update'
  post '/users/confirm_update' => 'users#confirm_update'

get 'users/confirmEmail'
post 'users/forgetPassword'

get 'users/changePassword', to: 'users#changePassword'

  # create (post) action for when log in form is submitted:
  post '/login'    => 'sessions#create'
  
  # delete action to log out:
  get '/logout' => 'sessions#destroy' 
  resources :posts
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts 
    # foreign_key: "updated_user_id,deleted_user_id"
    has_secure_password
    # validates :name, presence: true, uniqueness: true
    validates :email,
    presence: true,
    uniqueness: {case_sensitive: false},
    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
    validates :password_digest, presence:true, confirmation: true
    # validates_confirmation_of :password
    # validate :verify_old_password
    # validates :profile_photo, presence:true
    # validates :user_type, presence:true
    # validates :created_user_id, presence:true
    # validates :updated_user_id, presence:true
  def self.search(search)
      p 'SEARCH'
      if search
        User.where("name LIKE :name", {:name => "%#{search}%"})
        # find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
      else
        find(:all)
      end
  end

    
  def self.authenticate email, password
    User.find_by_email(email).try(:authenticate, password)
  end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authorize, only: [:index, :new, :edit,:update]
    # before_action :redirect_cancel, only: [:create, :update]
    def new
        @user = User.new
    end
    def index
        if params[:search]           
            @users = User.all.where("id != ?", current_user.id).search(params[:search]).paginate(page: params[:page], per_page: 5)
        else           
           # @users =  User.all.where("id NOT IN(?)", current_user.id)
           @users = User.all.where("id != ?", current_user.id).paginate(page: params[:page], per_page: 5)
         end 
    end

    def show
        p "SHOW"
        @user = User.find(params[:id])
    end

    def register
        @user=User.new
    end

    def confirm
        p "Confirm user"   
        @user = User.new(user_params)
        p "User data #{@user.inspect}"
        render "confirm_user", status: :unprocessable_entity
    end
    def create
        p "Create user"  
        @user = User.new(user_params)
        p "User data #{user_params.inspect}"
        # store all emails in lowercase to avoid duplicates and case-sensitive login errors:
        @user.email.downcase!
    
        if @user.save
        # If user saves in the db successfully:
        flash[:notice] = "User created successfully!"
        redirect_to users_path
        else
        # If user fails model validation - probably a bad password or duplicate email:
        flash.now.alert = "Oops, couldn't create user. Please make sure you are using a valid email and password and try again."
        render :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def confirm_update
        @user = User.new(user_params)  
        p "UPDATE_Confirm_USER"
        render "confirm_user_update" , status: :unprocessable_entity
    end

    def update
        p 'Update user '
        user = User.find(params[:id])
        user.updated_user_id = session[:user_id]
        if user.update
            flash[:notice] = "User updated successfully!"
            redirect_to posts_path
        else        
            flash.now.alert = "Oops, couldn't create post. Please try again."
            render :new, status: :unprocessable_entity
        end         
        redirect_to users_path
    end

    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to user_path
    end  

    def confirmEmail
        @user = User.find(params[:id])
        
    end

    def changePassword
    end
    def passwordChange
    end
    def change_password
    @user = User.find(session[:user_id])
    p "user data #{@user.inspect}"
    current_password = params[:current_password]
    p "current password #{current_password.inspect}"
    user = User.authenticate(@user.email, current_password)
    p "user authenticate  #{user.inspect}"
        if @user && user
            # @user.update.password = params[:new_password]
            # new_password = params[:password]
            # @user.update(new_password)
            user.update_attribute(password: params[:current_password])
            flash[:notice] = "Password successfully changed!"
            redirect_to user_path(session[:user_id])
        else
            flash[:notice] = "Your old password was incorrect. Please try again."
            
            redirect_to user_path(session[:user_id])
        end
    end

    private
        def change_password_params
            params.require(:user).permit(:old_password, :password, :password_confirmation)
        end

        def user_params
            params.require(:user).permit(:name, :email, :phone, :address, :date_of_birth, :profile_photo, :password, :password_confirmation)
        end

    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/changePassword.html.erb
<h1>Change Password</h1>

app/views/users/confirmEmail.html.erb
<div class="container"> 
<h2>Email confirmation</h2><br>
<%= form_for @users, :url =>{:action => "forgetPassword", :email => @user} do |form| %>
<div class="form-group">
    <%= form.label :email %>
    <%= text_field :email, class: 'form-control' %>
</div>
<div class="form-group">
<label>Password:</label><br/>
<%= password_field_tag :password, params[:password] , class:'form-control' %>
</div><br>

<%= submit_tag "Continue", class:'btn btn-primary' %>
<%= link_to 'Back', login_path %>

<% end -%>
</div>

app/views/users/confirm_user.html.erb
<div class="container">
    <div class="row justify-content-md-center">
        <div class="row justify-content-center">
            <h4 class="mt-6 mb-6 display-6">Confirm User</h4>
        </div>
        <div class="col-8">
            <%= form_with(model: @user, local: true) do |form| %>
                <div class="form-group">
                    <%= form.label :name %>
                    <%= form.text_field :name, :readonly => true, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= form.label :email %>
                    <%= form.text_field :email, :readonly => true, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= form.label :address %>
                    <%= form.text_area :address, :readonly => true, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= form.label :phone %>
                    <%= form.number_field :phone, :readonly => true, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= form.label :date_of_birth %>
                    <%= form.date_field :date_of_birth, :readonly => true, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= form.label :profile_photo %>
                    <%= form.text_field :profile_photo, :readonly => true, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= form.label :password %>
                    <%= form.password_field :password, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= form.label :password %>
                    <%= form.password_field :password_confirmation, class: 'form-control' %>
                </div>
                <div class="form-group">
                     <%= form.submit "Confirm", class: 'btn btn-primary' %>
                     <%= link_to 'Back.', 'javascript:history.back()', :class => "btn btn-primary" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">Edit User</h4>
  </div>
  <div class="row justify-content-center">
  <%= form_with(model: @user, local: true) do |form| %>  
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :phone %>
        <%= form.text_field :phone, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_area :address, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :date_of_birth %>
        <%= form.date_field :date_of_birth, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.submit "Update", class: 'form-control btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="row justify-content-center">
  <h4 class="mt-4 display-4">User List</h4>
</div>
<div class="row justify-content-center">
 
</div>
<div class="row justify-content-center" >
<%= form_tag(users_path, method: 'get') do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag("Search") %> 
<% end %>
<%= button_to "Create User", register_path, method: :get, class:"btn-success mt-4", style:"margin-bottom:10px"%>

<div>
<% if @users.present? %>
  <div class="row justify-content-center">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col" colspan="3">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td style="width: 60px;"><%= link_to 'Show', user_path(user.id), class: 'form-control btn-primary' %></td>    
            <td style="width: 60px;"><%= link_to 'Edit', edit_user_path(user.id), class: 'form-control btn-primary' %></td>          
            <td style="width: 60px;"><%= link_to 'Delete', user_path(user.id), class: 'form-control btn-danger', data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure to delete?"
            } %></td>   
            </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @users, renderer: BootstrapPagination::Rails %>

  </div>
<% else %>
  <div class="p-3 mb-2 bg-light text-dark">
    <span class="text-info font-weight-bold">Welcome! </span>
    Create your first user
  </div>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

 <%= form_for @user do |f| %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Sign up!" %>
  </div>
<% end %>

app/views/users/register.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">New User</h4>
  </div>
  <div class="row justify-content-center">
  <%= form_for @user, :url =>{:action => "confirm"}  do |form| %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, autofocus: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_area :address, class: 'form-control' %>
     </div>
     <div class="form-group">
        <%= form.label :phone %>
        <%= form.number_field :phone, class: 'form-control' %>
     </div>
     <div class="form-group">
        <%= form.label :date_of_birth %>
        <%= form.date_field :date_of_birth, class: 'form-control' %>
     </div>
     <div class="form-group">
        <%= form.label :profile_photo %>
        <%= form.text_field  :profile_photo, class: 'form-control' %>
      </div>
    <br>
    <div class="form-group">
        <%= form.submit "Create User",class: 'btn-success'  %>
        <%= submit_tag("Clear", { :name => 'reset', :id => 'reset_button', :type => "reset", :class => 'btn-primary'}) %>
    </div>
    <br>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">User <%= @user.id %> Detail</h4>
  </div>
  <div class="row justify-content-center">
    <table class="table">
      <tbody>
        <tr>
          <th>Name:</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>Email:</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th>Address:</th>
          <td><%= @user.address %></td>
       </tr>
       <tr>
        <th>Phone:</th>
        <td><%= @user.phone %></td>
      </tr>
      <tr>
        <th>Date of birth:</th>
        <td><%= @user.date_of_birth %></td>
      </tr>
      </tbody>
    </table>
    <%= button_to "Edit", edit_user_path(@user.id), method: :get, class:"btn-success mt-8"%>
  </div>
</div>