config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'sessions#new'
  	
  # sign up page with form:
  get 'users/new' => 'users#new', as: :new_user

  # create (post) action for when sign up form is submitted:

  # resources :posts do
  #   collection do
  #     get :confirm_create, to: "posts#new"
  #     post :confirm_create
  #   end
  #   member do
  #     get :confirm_update, to: "posts#confirm_update"
  #     post :confirm_update
  #     post :update_post
  #   end
  # end


  # , only: [:index, :create, :update, :edit, :destroy]
  # get '/users' => 'users#index'
  #  get '/users/:id', to: 'users#profile'
  # log in page with form:
  get '/login'     => 'sessions#new'
  get '/register'     => 'users#register'
  post '/posts/import' => 'posts#import'

  post '/posts/confirm' => 'posts#confirm'
  
  post '/users/confirm' => 'users#confirm'
  post '/posts/confirm_update' => 'posts#confirm_update'
  post '/users/confirm_update' => 'users#confirm_update'

get 'users/confirmEmail'
post 'users/forgetPassword'

get 'users/changePassword', to: 'users#changePassword'

  # create (post) action for when log in form is submitted:
  post '/login'    => 'sessions#create'
  
  # delete action to log out:
  get '/logout' => 'sessions#destroy' 
  resources :posts
  resources :users
end

app/views/layouts/_footer.html.erb
<div class="footer-bottom">
   <p style="font-style:bold;font-size:2em">Seattle Consulting Myanmar</p>
   <p>Copyright © Seattle Consulting Myanmar Co., Ltd. All rights reserved.</p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #a0b9a4;">
  <a class="navbar-brand" href="#">BulletInBoard</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to 'Home', root_path, class:"nav-link" %> 
        </li>
        <% if current_user %>
            <li class="nav-item">      
                <%= link_to 'Users', users_path, class:"nav-link" %> 
            </li>  
            <li class="nav-item">      
                <%= link_to 'Posts', posts_path, class:"nav-link" %> 
            </li>  


            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <% if current_user %>
              <%= "#{current_user.name}" %>
              <% end %>

            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Profile', user_path(current_user.id), class: 'dropdown-item' %>
              <%= link_to 'Change Password', users_changePassword_path, class: 'dropdown-item' %>   
              <%= link_to 'Log Out', logout_path, method: :delete, class:"dropdown-item" %>      
            </div>
          </li>

        <% else %> 
            <li class="nav-item">      
                <%= link_to 'Log In', login_path, class:"nav-link" %> 
            </li>
            <li class="nav-item">      
                <%= link_to 'Sign Up', new_user_path, class:"nav-link" %>
            </li> 
      
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <style>
  .footer-bottom{
    background: #b7ddb7;
    width: 100vw;
    padding: 20px;
    padding-bottom: 40px;
    text-align: center;
}
  </style>
    <title>BulletInBoard3</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
  integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    
    <!-- show flash message if any: -->
    <div class="alert">
      <% if notice %>
        <%= notice %>
      <% end %>
    </div>
    <% if alert %>
      <%= alert %>
    <% end %>
    <!-- end -->
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>